/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.company;

class MessageUtils {
    public static String getMessage() {
        return "Made by Arnau Barra";
    }
}
